// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: proto/status.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ServerStatusClient is the client API for ServerStatus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerStatusClient interface {
	GetServerStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerStatusResponse, error)
}

type serverStatusClient struct {
	cc grpc.ClientConnInterface
}

func NewServerStatusClient(cc grpc.ClientConnInterface) ServerStatusClient {
	return &serverStatusClient{cc}
}

func (c *serverStatusClient) GetServerStatus(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerStatusResponse, error) {
	out := new(ServerStatusResponse)
	err := c.cc.Invoke(ctx, "/ServerStatus/GetServerStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerStatusServer is the server API for ServerStatus service.
// All implementations must embed UnimplementedServerStatusServer
// for forward compatibility
type ServerStatusServer interface {
	GetServerStatus(context.Context, *Empty) (*ServerStatusResponse, error)
	mustEmbedUnimplementedServerStatusServer()
}

// UnimplementedServerStatusServer must be embedded to have forward compatible implementations.
type UnimplementedServerStatusServer struct {
}

func (UnimplementedServerStatusServer) GetServerStatus(context.Context, *Empty) (*ServerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServerStatus not implemented")
}
func (UnimplementedServerStatusServer) mustEmbedUnimplementedServerStatusServer() {}

// UnsafeServerStatusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerStatusServer will
// result in compilation errors.
type UnsafeServerStatusServer interface {
	mustEmbedUnimplementedServerStatusServer()
}

func RegisterServerStatusServer(s grpc.ServiceRegistrar, srv ServerStatusServer) {
	s.RegisterService(&ServerStatus_ServiceDesc, srv)
}

func _ServerStatus_GetServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerStatusServer).GetServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ServerStatus/GetServerStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerStatusServer).GetServerStatus(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ServerStatus_ServiceDesc is the grpc.ServiceDesc for ServerStatus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServerStatus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ServerStatus",
	HandlerType: (*ServerStatusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetServerStatus",
			Handler:    _ServerStatus_GetServerStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/status.proto",
}
